export const FETCH_ROOMS = 'FETCH_ROOMS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INSERT_PRODUCT = 'INSERT_PRODUCT';
export const INSERT_TABLE = 'INSERT_TABLE';
//////////////////FOR TABLE///////////////////
export const FETCH_COUNT_TABLES = 'FETCH_COUNT_TABLES';
export const FETCH_INDEX_TABLES = 'FETCH_INDEX_TABLES';
export const SEARCH_PRODUCT = 'INSERT_PRODUCT';
export const FETCH_TABLES = 'FETCH_TABLES';
export const FETCH_STTTABLE = 'FETCH_STTTABLE';
export const ONCHANGE_TABLE = 'ONCHANGE_TABLE';
export const ONCHANGE_ROOM = 'ONCHANGE_ROOM';
export const ONCHANGE_STATUS = 'ONCHANGE_STATUS';
export const CHANGE_NAVIGATION = 'CHANGE_NAVIGATION';
export const CHANGE_TABLE_IDTABLE = 'CHANGE_TABLE_IDTABLE';
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME';
export const CHANGE_TABLE_IDAREA = 'CHANGE_TABLE_IDAREA';
export const CHANGE_TABLE_STATUS = 'CHANGE_TABLE_STATUS';

///////////FOR MODAL///////////////
export const MODAL_HEADER_FOR_INSERT_UPDATE_TABLE = 'MODAL_HEADER_FOR_INSERT_UPDATE_TABLE';
export const MODAL_HEADER_FOR_ONTAP_TABLE = 'MODAL_HEADER_FOR_ONTAP_TABLE';
export const MODAL_HEADER_FOR_INSERT_UPDATE_ROOM = 'MODAL_HEADER_FOR_INSERT_UPDATE_ROOM';
export const MODAL_HEADER_FOR_ONTAP_ROOM = 'MODAL_HEADER_FOR_ONTAP_ROOM';

///////FOR FORM ROOM ////////////
export const CHANGE_ROOM_IDROOM = 'CHANGE_ROOM_IDROOM';
export const CHANGE_ROOM_NAMEROOM = 'CHANGE_ROOM_NAMEROOM';
export const CHANGE_ROOM_IDIDROOM = 'CHANGE_ROOM_IDIDROOM';
export const CHANGE_ROOM_NAME_SEARCH = 'CHANGE_ROOM_NAME_SEARCH';

///////FOR STATUS ///////
export const STATUS_EVENT_UPDATE_DELETE_INSERT = 'STATUS_EVENT_UPDATE_DELETE_INSERT';

//////STYLE EVENT ///////////
export const STATUS_STYLE_EVENT = 'STATUS_STYLE_EVENT';

///ONTAP//////////
export const ONTAP_CHANGE_ROOM = 'ONTAP_CHANGE_ROOM';
export const ONTAP_CHANGE_TABLE = 'ONTAP_CHANGE_TABLE';
export const ONTAP_CHANGE_BUTTON_TABLE = 'ONTAP_CHANGE_BUTTON_TABLE';
export const ONTAP_CHANGE_BUTTON_ROOM = 'ONTAP_CHANGE_BUTTON_ROOM';

/////////FORM ////////////

export const CHANGE_CUSTOMER_IDSUPPLIER = 'CHANGE_CUSTOMER_IDSUPPLIER';
export const CHANGE_CUSTOMER_NAMESUPPLIER = 'CHANGE_CUSTOMER_NAMESUPPLIER';
export const CHANGE_CUSTOMER_EMAILSUPPLIER = 'CHANGE_CUSTOMER_EMAILSUPPLIER';
export const CHANGE_CUSTOMER_PHONESUPPLIER = 'CHANGE_CUSTOMER_PHONESUPPLIER';
export const CHANGE_CUSTOMER_ADDRESSSUPPLIER = 'CHANGE_CUSTOMER_ADDRESSSUPPLIER';
export const CHANGE_CUSTOMER_NOTESUPPLIER = 'CHANGE_CUSTOMER_NOTESUPPLIER';
export const CHANGE_CUSTOMER_DEBITSUPPLIER = 'CHANGE_CUSTOMER_DEBITSUPPLIER';
export const CHANGE_CUSTOMER_AVATARSUPPLIER = 'CHANGE_CUSTOMER_AVATARSUPPLIER';
export const CHANGE_ID_NAME_SEARCH_SUPPLIER = 'CHANGE_ID_NAME_SEARCH_SUPPLIER';
export const CHANGE_DEBIT_SEARCH_SUPPLIER = 'CHANGE_DEBIT_SEARCH_SUPPLIER';
export const CHANGE_INDEX_SUPPLIER ='CHANGE_INDEX_SUPPLIER';